### ISSUE TITLE
DB tables not created

### ISSUE THREAD

**Issue by maggie44** [atinux/atidone#26]
When deploying this directly from the Hub dashboard the D1 tables are not created. I had to link the local dev environment to the project then run `pnpm dev --remote` to have the migrations run and for the tables to be created.

Took a while to figure this out and doesn't look so great for the Hub when the demo isn't working without the CLI.

**Comment by atinux** [comment]
Sorry about this, going to fix this very soon!

**Comment by atinux** [comment]
This should be now fixed thanks to https://hub.nuxt.com/changelog/database-migrations

The template is now up to date!
